
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todosdb
    username: root
    password: admin
  jpa:
    show-sql: true

springdoc:
  swagger-ui:
    path=/swagger-ui.html
